apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-server
  namespace: jenkins
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-server
        image: nexus-docker.minikube/webapp:1.0
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 8080
          protocol: TCP        
        imagePullSecrets:
        - name: nexus-docker-credentials
