apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nexus-docker.minikube/i.b.vermeg:webapp
        ports:
        - name: http-port
          containerPort: 8080
          protocol: TCP
        imagePullSecrets:
        - name: nexus-docker-credentials
